name: Build -> gulpegaspe-os ISO

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: self-hosted # Oppure 'ubuntu-latest' se configuri i permessi di root
    #runs-on: ubuntu-latest
    #permissions:
    #  contents: read
    #  packages: write  # Permission required to write to GitHub Packages
    
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v7

      - name: Set up output directory
        run: mkdir -p output

      - name: Pull target OS image
        run: sudo podman pull ghcr.io/gulpegaspe/gulpegaspe-os:latest

      - name: Run bootc-image-builder via Podman
        run: |
          sudo podman run --rm -it --privileged \
            --pull=newer \
            -v ./output:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            -v ./iso-builder/config.toml:/config.toml:ro \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type anaconda-iso \
            --rootfs btrfs \
            ghcr.io/gulpegaspe/gulpegaspe-os

      #- name: Fix output permissions
      #  run: sudo chown -R $USER:$USER output/
      
      #- name: Upload ISO Artifact
      #  uses: actions/upload-artifact@v7
      #  with:
      #    name: gulpegaspe-os-iso
      #    path: output/**/*.iso

      - name: Publish release with ISO
        uses: softprops/action-gh-release@v2
        with:
          files: output/**/*.iso
          # Se vuoi che crei una release "automatica" ogni volta (es. sovrascrivendo una tag "latest"):
          tag_name: latest
          name: "Gulpegaspe OS - Latest Build"
          body: "Automatic build of Gulpegaspe OS ISO generated via bootc-image-builder."
          draft: true
          #prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
